name : checking out code
on : [push]
jobs:
    checkoutcode:
        runs-on: ubuntu-latest
        steps:
            - name : checkout repo
              uses: actions/checkout@v4
              with:
                repository: rakeshirukula/ThreeTier.git
